title: Kovarianzmatrix ausrechnen
question: |
  Gegeben ist eine Matrix \( X \) mit drei Merkmalen und zehn Beobachtungen:

  \[
  X =
  \begin{pmatrix}
  2 & 7 & 2 \\
  4 & 8 & 6 \\
  2 & 6 & 1 \\
  7 & 6 & 3 \\
  1 & 5 & 9 \\
  1 & 4 & 6 \\
  2 & 6 & 8 \\
  1 & 8 & 3 \\
  4 & 6 & 7 \\
  6 & 4 & 5
  \end{pmatrix}
  \]

  Dabei entspricht jede Spalte einem Merkmal und jede Zeile einer Beobachtung.
  
  Bestimmen Sie die **Kovarianzmatrix**.

tip: Die Matrix sollte dir bekannt vorkommen😉
solution: |
  \[
  \begin{pmatrix}
   4.2 & -0.3 & -0.7 \\
  -0.3 &  1.8 & -1.1 \\
  -0.7 & -1.1 &  6.4
  \end{pmatrix}
  \]
