title: Pareto Verteilung 3
question: |
  Welche Funktion beschreibt die Wahrscheinlichkeitsdichte der Pareto-Verteilung?

  A) $f(x) = \frac{Œ±*x_{min}^Œ±}{x^{Œ±+1}} \text{, f√ºr } x \geq x_m$
  
  B) $f(x) = \frac{1}{x^a} \text{, f√ºr } x \geq 0$
  
  C) $f(x) = \frac{1}{x^2} \text{, f√ºr } x \geq 1$
  
  D) $f(x) = ùõºx^a_me^{-ax} \text{, f√ºr x } \geq x_m$

solution: A
