title: Relative H채ufigkeiten berechnen
question: |
  Erstelle eine funktion `relative_counts`, die eine Liste mit absoluten H채ufigkeiten erh채lt
  und aus dieser die Liste mit relativen H채ufigkeiten berechnet. 
  ```python
  relative_counts([4, 5, 15, 17, 10]) # [0.08, 0.1, 0.29, 0.33, 0.2]
  ```
