title: "1) Umsätze in 4 Märkten"
question: |
  Gegeben sind in 4 Märkten folgende Verteilungen des Gesamtumsatzes auf die verschiedenen konkurrierenden Firmen:

  | Firma    | Markt 1 | Markt 2 | Markt 3 |
  |----------|---------|---------|---------|
  | Firma A  | 40      | 15      | 25      |
  | Firma B  | 10      | 30      | 20      |
  | Firma C  | 10      | 10      | 15      | 
  | Firma D  | 0       | 10      | 10      | 
  | Firma E  | 0       | 0       | 5       | 

  **Aufgabe:** 
  (a) Erstelle die Lorenzkurve für jeden Markt.

  (b) Berechne den normierten Gini-Koeffizienten G* für jeden Markt.

solution: |
  a)
  
  ![](gini_1a.png)

  b) 

  |    | Markt 1 | Markt 2 | Markt 3 |
  |----|---------|---------|---------|
  | G  | 0.6     | 0.4     | 0.2666  |
  | G* | 0.75    | 0.5     | 0.3333  |
 
