title: Poisson Verteilung 2
question: |
  Wie verändert sich die Poisson-Verteilung, wenn λ kleiner wird?
  
  A) Die Verteilung wird enger um den Mittelwert
  
  B) Die Verteilung wird breiter
  
  C) Die Verteilung wird symmetrisch
  
  D) Die Verteilung wird asymmetrisch

solution: A, D
