title: "3) Eigenvektoren berechnen (3x3 Matrizen)"
question: |
  Berechne die Eigenvektoren der folgenden Matrizen:

  a)

  \begin{pmatrix}
  1 & 2 & -1 \\
  0 & 3 & 0 \\
  -1 & 2 & 1
  \end{pmatrix}

  b)

  \begin{pmatrix}
  2 & 1 & -2 \\
  1 & 2 & 2 \\
  -2 & 2 & -1
  \end{pmatrix}

  c)

  \begin{pmatrix}
  2 & -1 & 2 \\
  -1 & 10 & -2 \\
  2 & -2 & 5
  \end{pmatrix}

solution: |
  a) $\lambda \cdot (\lambda -2) \cdot (3-\lambda)=0$

  $\lambda_{1}=0$ und $\lambda_{2}=2$ und $\lambda_{3}=3$

  $v_{1}= \begin{pmatrix}  1 \\  0 \\ 1 \end{pmatrix}$ und 
  $v_{2}= \begin{pmatrix}   -1 \\  0 \\ 1 \end{pmatrix}$ und 
  $v_{3}= \begin{pmatrix}   2 \\  3 \\ 2 \end{pmatrix}$

  b) $(\lambda -3) \cdot (-\lambda^2+9)=0$

  $\lambda_{1}=-3$ und $\lambda_{2}=3$ und $\lambda_{3}=3$

  $v_{1}= \begin{pmatrix}  \frac{1}{2} \\  -\frac{1}{2} \\ 1 \end{pmatrix}$ und 
  $v_{2}= \begin{pmatrix}   1 \\  1 \\ 0 \end{pmatrix}$ und 
  $v_{3}= \begin{pmatrix}   -2 \\  0 \\ 1 \end{pmatrix}$

  c) $(5- \lambda) \cdot (\lambda^2 -12 \cdot \lambda + 11)=0$

  $\lambda_{1}=5$ und $\lambda_{2}=1$ und $\lambda_{3}=11$

  $v_{1}= \begin{pmatrix}  1 \\  1 \\ 2 \end{pmatrix}$ und 
  $v_{2}= \begin{pmatrix}   -2 \\  0 \\ 1 \end{pmatrix}$ und 
  $v_{3}= \begin{pmatrix}   -1 \\  5 \\ -2 \end{pmatrix}$
 