title: Normalenvektor bestimmen
question: |
  Gegeben sei eine Ebene 

  $$
  E: x = r\cdot \begin{pmatrix} -3 \\ 3 \\ 4 \end{pmatrix} + s\cdot \begin{pmatrix} 12 \\ 5 \\ 1 \end{pmatrix}
  $$

  Finde einen Normalenvektor der Ebene. Wie viele Normalnvektoren gibt es?
tip: Stelle ein Lineares Gleichungsssystem auf. Die Unbekannten sind die Koordinaten des Normalenvektors.
solution: |
  Um den Normalenvektor der Ebene zu bestimmen, benötigen wir einen Vektor, der senkrecht auf beiden Richtungsvektoren steht. Dies erreichen wir, indem wir ein lineares Gleichungssystem (LGS) zur Bestimmung eines solchen Vektors \(\mathbf{n} = (a, b, c)^T\) aufstellen.

  Der Normalenvektor muss orthogonal zu den beiden Spannvektoren sein:

  \[
  \begin{pmatrix} -3 \\ 3 \\ 4 \end{pmatrix}^t \cdot \begin{pmatrix} a \\ b \\ c \end{pmatrix} = 0
  \]

  \[
  \begin{pmatrix} 12 \\ 5 \\ 1 \end{pmatrix}^t \cdot \begin{pmatrix} a \\ b \\ c \end{pmatrix} = 0
  \]

  Dies ergibt das lineare Gleichungssystem:

  \[
  -3a + 3b + 4c = 0
  \]

  \[
  12a + 5b + c = 0
  \]

  Um eine Lösung zu finden, setzen wir \( c = 1 \) (eine beliebige Wahl zur Bestimmung eines konkreten Normalenvektors):

  \[
  -3a + 3b + 4 = 0
  \]

  \[
  12a + 5b + 1 = 0
  \]

  Umgeformt:

  \[
  -3a + 3b = -4
  \]

  \[
  12a + 5b = -1
  \]

  Lösen durch das Additionsverfahren:

  Multiplizieren der ersten Gleichung mit 4:

  \[
  -12a + 12b = -16
  \]

  Addition mit der zweiten Gleichung:

  \[
  (-12a + 12b) + (12a + 5b) = -16 -1
  \]

  \[
  17b = -17
  \]

  \[
  b = -1
  \]

  Einsetzen von \( b = -1 \) in \( -3a + 3(-1) = -4 \):

  \[
  -3a - 3 = -4
  \]

  \[
  -3a = -1
  \]

  \[
  a = \frac{1}{3}
  \]

  Damit ergibt sich ein Normalenvektor:

  \[
  \mathbf{n} = \begin{pmatrix} \frac{1}{3} \\ -1 \\ 1 \end{pmatrix}
  \]
  
  Wir hatten zu Beginn $c=1$ gesetzt. Natürlich ist auch jedes vielfache von $\mathbf{n}$ ein Normalenvektor.
