title: Projektion von Punkten auf Vektoren
question: |
  Gegeben sind die folgenden Punkte und Vektoren in unterschiedlichen Dimensionen:

  **2D:**
  
  \[
  w_1 = \begin{pmatrix} 3 \\ 4 \end{pmatrix}, \quad
  w_2 = \begin{pmatrix} -2 \\ 1 \end{pmatrix}
  \]
  
  \[
  v_1 = \begin{pmatrix} 1 \\ 0 \end{pmatrix}, \quad
  v_2 = \begin{pmatrix} 0 \\ 1 \end{pmatrix} \quad
  \]

  **3D:**
  
  \[
  w_3 = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}, \quad
  w_4 = \begin{pmatrix} -1 \\ 0 \\ 2 \end{pmatrix}
  \]
  
  \[
  v_3 = \begin{pmatrix} 0 \\ 1 \\ 0 \end{pmatrix} \quad
  v_4 = \begin{pmatrix} 1 \\ 1 \\ 1 \end{pmatrix}
  \]

  **4D:**
  
  \[
  w_5 = \begin{pmatrix} 2 \\ -1 \\ 3 \\ 4 \end{pmatrix}, \quad
  w_6 = \begin{pmatrix} 0 \\ 2 \\ -1 \\ 1 \end{pmatrix}
  \]
  
  \[
  v_5 = \begin{pmatrix} 2 \\ 1 \\ 2 \\ 1 \end{pmatrix}, \quad
  v_6 = \begin{pmatrix} 1 \\ 0 \\ 0 \\ 0 \end{pmatrix} \quad
  \]

  Bestimmen Sie die Projektionen der Punkte auf die jeweiligen Vektoren.
  
  Berechnen Sie dann die L채nge der Projektionen.

solution: |
  **Berechnung der L채ngen der Vektoren**

  | Vektor $v$ | L채nge von $v$ |
  |--------------|------------|
  | $v_1$ | $1.0$ |
  | $v_2$ | $1.0$ |
  | $v_3$ | $1.0$ |
  | $v_4$ | $1.73$ |
  | $v_5$ | $3.16$ |
  | $v_6$ | $1.0$ |

  
  **Berechnung der Projektionen:**

  | Punkt $w$ | Vektor $v$ | Projektion $pr_v(w)$ | ~L채nge von $pr_v(p)$ |
  |--------------|--------------|--------------------------|----------------|
  | $w_1$ | $v_1$ | $(3, 0)$ | $3$ |
  | $w_1$ | $v_2$ | $(4, 4)$ | $4$ |
  | $w_2$ | $v_1$ | $(-2, 0)$ | $2$ |
  | $w_2$ | $v_2$ | $(-0.5, -0.5)$ | $0.71$ |
  | $w_3$ | $v_3$ | $(0, 2, 0)$ | $2$ |
  | $w_3$ | $v_4$ | $(2, 2, 2)$ | $3.46$ |
  | $w_4$ | $v_3$ | $(0, 0, 0)$ | $0$ |
  | $w_4$ | $v_4$ | $(\frac{1}{3}, \frac{1}{3}, \frac{1}{3})$ | $0.58$ |
  | $w_5$ | $v_5$ | $(2.6, 1.3, 2.6, 1.3)$ | $4.11$ |
  | $w_5$ | $v_6$ | $(2, 0, 0, 0)$ | $2.0$ |
  | $w_6$ | $v_5$ | $(0.2, 0.1, 0.2, 0.1)$ | $0.32$ |
  | $w_6$ | $v_6$ | $(0, 0, 0, 0)$ | $0.0$ |
