title: Exponentielle Verteilung 3
question: |
  Wann ist der Wert von λ in der Poisson-Verteilung am größten?
  
  A) Wenn die Ereignisse sehr selten sind
  
  B) Wenn die Ereignisse sehr häufig sind
  
  C) Wenn die Ereignisse unabhängig voneinander auftreten
  
  D) Wenn die Ereignisse in einem festen Intervall auftreten

solution: B
