title: "1) Daten zu Neugeborenen darstellen"
question: |
  Für 10 neugeborene Babys sind die nach der Geburt gemessenen Daten für die Größe (in cm) und das Gewicht (in kg) in dieser Tabelle dargestellt: 

  | Größe (cm)    | 52  | 50  | 53  | 50  | 54  | 53  | 52  | 50  | 48  | 49  |
  |---------------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
  | Gewicht (kg)  | 3,7 | 3,2 | 3,5 | 3,4 | 4   | 4,2 | 3,1 | 2,9 | 2,7 | 3,5 |

  (i) _
 
  (ii) _

  (iii) _

tip: Einteilung Klassen _


solution: |
  Coming soon! \(^.^)/
 
