title: Varianzen bei Projekt
question: |
  Gegeben ist eine Matrix \( X \) mit drei Merkmalen und fünf Beobachtungen:

  \[
  X =
  \begin{pmatrix}
  2 & 7 & 2 \\
  4 & 8 & 6 \\
  2 & 6 & 1 \\
  7 & 6 & 3 \\
  1 & 5 & 9 \\
  1 & 4 & 6 \\
  2 & 6 & 8 \\
  1 & 8 & 3 \\
  4 & 6 & 7 \\
  6 & 4 & 5
  \end{pmatrix}
  \]

  Dabei entspricht jede Spalte einem Merkmal und jede Zeile einer Beobachtung.
  
  Projiziere die Daten Auf die Vektor $v_1 = (1,0,0)^t,v_2 = (2,0,0)^t,v_3 = (1, -2, 0.5)^t$
  
  Berechne die Varianzen von $pr_{v_1}(X), pr_{v_2}(X)$ und $pr_{v_3}(X)$ auf zwei Weisen:
  
  * Unter Verwendung der Standardformel $\frac{1}{N} \sum_{i=1}^{N} (x_i - \bar{x})^2$,
  * unter Verwendung der hergeleiteten Formel $\frac{1}{|v|^4} v^t S v$.

