title: Matrix-Vektor-Multiplikation mit symmetrischer Matrix
question: |
  Gegeben sei die symmetrische Matrix
  
  \[
  A = \begin{pmatrix}
  4 & 2 & -1 \\
  2 & 3 & 0 \\
  -1 & 0 & 5
  \end{pmatrix}
  \]
  
  und der Vektor 
  
  \[
  x = \begin{pmatrix}
  x_1 \\ x_2 \\ x_3
  \end{pmatrix}
  \]
  
  Multipliziere einmal vollständig das Produkt \( x^t A x \) aus. 
  
  Bilde dann die partiellen Ableitungen \( \frac{\partial x^t A x}{\partial x_1} \), \( \frac{\partial x^t A x}{\partial x_2} \) und \( \frac{\partial x^t A x}{\partial x_3} \).

tip: Die Matrix ist symmetrisch, sodass sich die Terme beim Multiplizieren vereinfacht addieren lassen.
solution: |
  Wir berechnen zunächst \( x^t A x \):

  \[
  x^t A x =
  \begin{pmatrix} x_1 & x_2 & x_3 \end{pmatrix}
  \begin{pmatrix} 4 & 2 & -1 \\ 2 & 3 & 0 \\ -1 & 0 & 5 \end{pmatrix}
  \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix}
  \]

  Zunächst berechnen wir das Zwischenprodukt \( A x \):

  \[
  A x =
  \begin{pmatrix}
  4x_1 + 2x_2 - x_3 \\
  2x_1 + 3x_2 + 0x_3 \\
  -x_1 + 0x_2 + 5x_3
  \end{pmatrix}
  \]

  Jetzt folgt die Multiplikation mit \( x^t \):

  \[
  x^t A x =
  x_1 (4x_1 + 2x_2 - x_3) +
  x_2 (2x_1 + 3x_2 + 0x_3) +
  x_3 (-x_1 + 0x_2 + 5x_3)
  \]

  \[
  = 4x_1^2 + 2x_1x_2 - x_1x_3 + 2x_1x_2 + 3x_2^2 + 0x_2x_3 - x_1x_3 + 0x_2x_3 + 5x_3^2
  \]

  \[
  = 4x_1^2 + 4x_1x_2 - 2x_1x_3 + 3x_2^2 + 5x_3^2
  \]

  Nun berechnen wir die partiellen Ableitungen:

  \[
  \frac{\partial x^t A x}{\partial x_1} = 8x_1 + 4x_2 - 2x_3
  \]

  \[
  \frac{\partial x^t A x}{\partial x_2} = 4x_1 + 6x_2
  \]

  \[
  \frac{\partial x^t A x}{\partial x_3} = -2x_1 + 10x_3
  \]

  Insgesamt können wir die Ableitungen als Gradientenvektor notieren:

  \[
  \frac{\partial x^t A x}{\partial x} =
  \begin{pmatrix}
  8x_1 + 4x_2 - 2x_3 \\
  4x_1 + 6x_2 \\
  -2x_1 + 10x_3
  \end{pmatrix}
  \]
