title: Hypergeometrische Verteilung 1
question: |
  Welche der folgenden Aussagen trifft auf die hypergeometrische Verteilung zu?

  A) Sie modelliert die Wahrscheinlichkeit von Erfolgen in unabhängigen Bernoulli-Versuchen.  

  B) Sie beschreibt die Wahrscheinlichkeit von Erfolgen beim Ziehen ohne Zurücklegen aus einer endlichen Population.  

  C) Sie ist eine Approximation der Binomialverteilung für große Stichproben.  

  D) Sie wird verwendet, um die Zeit zwischen zwei Ereignissen zu modellieren.
solution: B